# Generated by Django 5.2.11 on 2026-03-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Nature', 'Nature'), ('Travel', 'Travel'), ('Food', 'Food'), ('Art', 'Art'), ('Lifestyle', 'Lifestyle'), ('Other', 'Other')], default='Other', max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
