# Generated by Django 5.2.11 on 2026-03-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='category',
            field=models.CharField(choices=[('Nature', 'Nature'), ('Travel', 'Travel'), ('Food', 'Food'), ('Art', 'Art'), ('Lifestyle', 'Lifestyle'), ('Technology', 'Technology'), ('Architecture', 'Architecture'), ('Fashion', 'Fashion'), ('Sports', 'Sports'), ('Animals', 'Animals'), ('People', 'People'), ('Events', 'Events'), ('Business', 'Business'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
